<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <RootNamespace>InduLink.Runtime</RootNamespace>
    <AssemblyName>InduLink.Runtime</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\InduLink.Abstractions\InduLink.Abstractions.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="8.0.0" />
  </ItemGroup>
</Project>
