namespace IndustrialCommMinimal.WinForms
{
    partial class MainForm
    {
        private System.ComponentModel.IContainer components = null;
        private System.Windows.Forms.TabControl ProtocolTabControl;
        private System.Windows.Forms.TabPage ModbusTcpTabPage, ModbusRtuTabPage, S7TabPage, McTabPage, RawTcpTabPage, MesTcpTabPage, MesHttpTabPage;
        private System.Windows.Forms.FlowLayoutPanel ModbusTcpPanel, ModbusRtuPanel, S7Panel, McPanel, RawTcpPanel, MesTcpPanel, MesHttpPanel;
        private System.Windows.Forms.TextBox ModbusTcpHostTextBox, ModbusTcpPortTextBox, ModbusTcpSlaveTextBox, ModbusTcpAddressTextBox, ModbusTcpValueTextBox, ModbusTcpOutputTextBox;
        private System.Windows.Forms.ComboBox ModbusTcpTypeComboBox;
        private System.Windows.Forms.Button ModbusTcpConnectButton, ModbusTcpReadButton, ModbusTcpWriteButton, ModbusTcpDisconnectButton;
        private System.Windows.Forms.TextBox ModbusRtuPortTextBox, ModbusRtuBaudTextBox, ModbusRtuSlaveTextBox, ModbusRtuAddressTextBox, ModbusRtuValueTextBox, ModbusRtuOutputTextBox;
        private System.Windows.Forms.ComboBox ModbusRtuTypeComboBox;
        private System.Windows.Forms.Button ModbusRtuConnectButton, ModbusRtuReadButton, ModbusRtuWriteButton, ModbusRtuDisconnectButton;
        private System.Windows.Forms.TextBox S7HostTextBox, S7RackTextBox, S7SlotTextBox, S7AddressTextBox, S7ValueTextBox, S7OutputTextBox;
        private System.Windows.Forms.ComboBox S7TypeComboBox;
        private System.Windows.Forms.Button S7ConnectButton, S7ReadButton, S7WriteButton, S7DisconnectButton;
        private System.Windows.Forms.TextBox McHostTextBox, McPortTextBox, McTimeoutTextBox, McAddressTextBox, McValueTextBox, McOutputTextBox;
        private System.Windows.Forms.ComboBox McTypeComboBox;
        private System.Windows.Forms.Button McConnectButton, McReadButton, McWriteButton, McDisconnectButton;
        private System.Windows.Forms.TextBox RawTcpHostTextBox, RawTcpPortTextBox, RawTcpPayloadTextBox, RawTcpOutputTextBox;
        private System.Windows.Forms.Button RawTcpConnectButton, RawTcpSendButton, RawTcpDisconnectButton;
        private System.Windows.Forms.TextBox MesTcpHostTextBox, MesTcpPortTextBox, MesTcpDeviceNoTextBox, MesTcpDeviceNameTextBox, MesTcpDeviceIpTextBox, MesTcpDeviceMacTextBox, MesTcpOutputTextBox;
        private System.Windows.Forms.Button MesTcpConnectButton, MesTcpOnlineButton, MesTcpDisconnectButton;
        private System.Windows.Forms.TextBox MesHttpUrlTextBox, MesHttpDeviceNoTextBox, MesHttpDeviceNameTextBox, MesHttpDeviceIpTextBox, MesHttpDeviceMacTextBox, MesHttpOutputTextBox;
        private System.Windows.Forms.Button MesHttpOnlineButton;

        protected override void Dispose(bool disposing)
        {
            if (disposing && components != null) components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.ProtocolTabControl = new System.Windows.Forms.TabControl();
            this.ModbusTcpTabPage = new System.Windows.Forms.TabPage(); this.ModbusRtuTabPage = new System.Windows.Forms.TabPage(); this.S7TabPage = new System.Windows.Forms.TabPage(); this.McTabPage = new System.Windows.Forms.TabPage(); this.RawTcpTabPage = new System.Windows.Forms.TabPage(); this.MesTcpTabPage = new System.Windows.Forms.TabPage(); this.MesHttpTabPage = new System.Windows.Forms.TabPage();
            this.ModbusTcpPanel = new System.Windows.Forms.FlowLayoutPanel(); this.ModbusRtuPanel = new System.Windows.Forms.FlowLayoutPanel(); this.S7Panel = new System.Windows.Forms.FlowLayoutPanel(); this.McPanel = new System.Windows.Forms.FlowLayoutPanel(); this.RawTcpPanel = new System.Windows.Forms.FlowLayoutPanel(); this.MesTcpPanel = new System.Windows.Forms.FlowLayoutPanel(); this.MesHttpPanel = new System.Windows.Forms.FlowLayoutPanel();
            this.ModbusTcpHostTextBox = NewTextBox("127.0.0.1"); this.ModbusTcpPortTextBox = NewTextBox("502"); this.ModbusTcpSlaveTextBox = NewTextBox("1"); this.ModbusTcpAddressTextBox = NewTextBox("D100"); this.ModbusTcpValueTextBox = NewTextBox("0"); this.ModbusTcpTypeComboBox = NewTypeComboBox(); this.ModbusTcpOutputTextBox = NewOutputTextBox();
            this.ModbusTcpConnectButton = NewButton("连接"); this.ModbusTcpReadButton = NewButton("读取"); this.ModbusTcpWriteButton = NewButton("写入"); this.ModbusTcpDisconnectButton = NewButton("断开");
            this.ModbusRtuPortTextBox = NewTextBox("COM3"); this.ModbusRtuBaudTextBox = NewTextBox("9600"); this.ModbusRtuSlaveTextBox = NewTextBox("1"); this.ModbusRtuAddressTextBox = NewTextBox("HR0"); this.ModbusRtuValueTextBox = NewTextBox("0"); this.ModbusRtuTypeComboBox = NewTypeComboBox(); this.ModbusRtuOutputTextBox = NewOutputTextBox();
            this.ModbusRtuConnectButton = NewButton("连接"); this.ModbusRtuReadButton = NewButton("读取"); this.ModbusRtuWriteButton = NewButton("写入"); this.ModbusRtuDisconnectButton = NewButton("断开");
            this.S7HostTextBox = NewTextBox("127.0.0.1"); this.S7RackTextBox = NewTextBox("0"); this.S7SlotTextBox = NewTextBox("1"); this.S7AddressTextBox = NewTextBox("DB1.DBW0"); this.S7ValueTextBox = NewTextBox("0"); this.S7TypeComboBox = NewTypeComboBox(); this.S7OutputTextBox = NewOutputTextBox();
            this.S7ConnectButton = NewButton("连接"); this.S7ReadButton = NewButton("读取"); this.S7WriteButton = NewButton("写入"); this.S7DisconnectButton = NewButton("断开");
            this.McHostTextBox = NewTextBox("127.0.0.1"); this.McPortTextBox = NewTextBox("5000"); this.McTimeoutTextBox = NewTextBox("5000"); this.McAddressTextBox = NewTextBox("D100"); this.McValueTextBox = NewTextBox("0"); this.McTypeComboBox = NewTypeComboBox(); this.McOutputTextBox = NewOutputTextBox();
            this.McConnectButton = NewButton("连接"); this.McReadButton = NewButton("读取"); this.McWriteButton = NewButton("写入"); this.McDisconnectButton = NewButton("断开");
            this.RawTcpHostTextBox = NewTextBox("127.0.0.1"); this.RawTcpPortTextBox = NewTextBox("9000"); this.RawTcpPayloadTextBox = NewTextBox("hello"); this.RawTcpOutputTextBox = NewOutputTextBox(); this.RawTcpConnectButton = NewButton("连接"); this.RawTcpSendButton = NewButton("发送并接收"); this.RawTcpDisconnectButton = NewButton("断开");
            this.MesTcpHostTextBox = NewTextBox("127.0.0.1"); this.MesTcpPortTextBox = NewTextBox("9312"); this.MesTcpDeviceNoTextBox = NewTextBox("DEVICE-001"); this.MesTcpDeviceNameTextBox = NewTextBox("MinimalClient"); this.MesTcpDeviceIpTextBox = NewTextBox("127.0.0.1"); this.MesTcpDeviceMacTextBox = NewTextBox("00-00-00-00-00-00"); this.MesTcpOutputTextBox = NewOutputTextBox(); this.MesTcpConnectButton = NewButton("连接"); this.MesTcpOnlineButton = NewButton("发送上线"); this.MesTcpDisconnectButton = NewButton("断开");
            this.MesHttpUrlTextBox = NewTextBox("http://127.0.0.1:8080/api"); this.MesHttpDeviceNoTextBox = NewTextBox("DEVICE-001"); this.MesHttpDeviceNameTextBox = NewTextBox("MinimalClient"); this.MesHttpDeviceIpTextBox = NewTextBox("127.0.0.1"); this.MesHttpDeviceMacTextBox = NewTextBox("00-00-00-00-00-00"); this.MesHttpOutputTextBox = NewOutputTextBox(); this.MesHttpOnlineButton = NewButton("发送上线");
            this.SuspendLayout();
            SetupPage(this.ModbusTcpTabPage, this.ModbusTcpPanel, "Modbus TCP", new System.Windows.Forms.Control[] { NewLabel("主机"), this.ModbusTcpHostTextBox, NewLabel("端口"), this.ModbusTcpPortTextBox, NewLabel("站号"), this.ModbusTcpSlaveTextBox, NewLabel("地址"), this.ModbusTcpAddressTextBox, NewLabel("数据类型"), this.ModbusTcpTypeComboBox, NewLabel("写入值"), this.ModbusTcpValueTextBox, this.ModbusTcpConnectButton, this.ModbusTcpReadButton, this.ModbusTcpWriteButton, this.ModbusTcpDisconnectButton, this.ModbusTcpOutputTextBox });
            SetupPage(this.ModbusRtuTabPage, this.ModbusRtuPanel, "Modbus RTU", new System.Windows.Forms.Control[] { NewLabel("串口"), this.ModbusRtuPortTextBox, NewLabel("波特率"), this.ModbusRtuBaudTextBox, NewLabel("站号"), this.ModbusRtuSlaveTextBox, NewLabel("地址"), this.ModbusRtuAddressTextBox, NewLabel("数据类型"), this.ModbusRtuTypeComboBox, NewLabel("写入值"), this.ModbusRtuValueTextBox, this.ModbusRtuConnectButton, this.ModbusRtuReadButton, this.ModbusRtuWriteButton, this.ModbusRtuDisconnectButton, this.ModbusRtuOutputTextBox });
            SetupPage(this.S7TabPage, this.S7Panel, "Siemens S7", new System.Windows.Forms.Control[] { NewLabel("主机"), this.S7HostTextBox, NewLabel("机架"), this.S7RackTextBox, NewLabel("插槽"), this.S7SlotTextBox, NewLabel("地址"), this.S7AddressTextBox, NewLabel("数据类型"), this.S7TypeComboBox, NewLabel("写入值"), this.S7ValueTextBox, this.S7ConnectButton, this.S7ReadButton, this.S7WriteButton, this.S7DisconnectButton, this.S7OutputTextBox });
            SetupPage(this.McTabPage, this.McPanel, "Mitsubishi MC", new System.Windows.Forms.Control[] { NewLabel("主机"), this.McHostTextBox, NewLabel("端口"), this.McPortTextBox, NewLabel("接收超时(ms)"), this.McTimeoutTextBox, NewLabel("地址"), this.McAddressTextBox, NewLabel("数据类型"), this.McTypeComboBox, NewLabel("写入值"), this.McValueTextBox, this.McConnectButton, this.McReadButton, this.McWriteButton, this.McDisconnectButton, this.McOutputTextBox });
            SetupPage(this.RawTcpTabPage, this.RawTcpPanel, "原始 TCP", new System.Windows.Forms.Control[] { NewLabel("主机"), this.RawTcpHostTextBox, NewLabel("端口"), this.RawTcpPortTextBox, NewLabel("发送文本"), this.RawTcpPayloadTextBox, this.RawTcpConnectButton, this.RawTcpSendButton, this.RawTcpDisconnectButton, this.RawTcpOutputTextBox });
            SetupPage(this.MesTcpTabPage, this.MesTcpPanel, "MES TCP", new System.Windows.Forms.Control[] { NewLabel("主机"), this.MesTcpHostTextBox, NewLabel("端口"), this.MesTcpPortTextBox, NewLabel("设备编号"), this.MesTcpDeviceNoTextBox, NewLabel("设备名称"), this.MesTcpDeviceNameTextBox, NewLabel("设备 IP"), this.MesTcpDeviceIpTextBox, NewLabel("设备 MAC"), this.MesTcpDeviceMacTextBox, this.MesTcpConnectButton, this.MesTcpOnlineButton, this.MesTcpDisconnectButton, this.MesTcpOutputTextBox });
            SetupPage(this.MesHttpTabPage, this.MesHttpPanel, "MES HTTP", new System.Windows.Forms.Control[] { NewLabel("API 地址"), this.MesHttpUrlTextBox, NewLabel("设备编号"), this.MesHttpDeviceNoTextBox, NewLabel("设备名称"), this.MesHttpDeviceNameTextBox, NewLabel("设备 IP"), this.MesHttpDeviceIpTextBox, NewLabel("设备 MAC"), this.MesHttpDeviceMacTextBox, this.MesHttpOnlineButton, this.MesHttpOutputTextBox });
            this.ProtocolTabControl.Controls.AddRange(new System.Windows.Forms.Control[] { this.ModbusTcpTabPage, this.ModbusRtuTabPage, this.S7TabPage, this.McTabPage, this.RawTcpTabPage, this.MesTcpTabPage, this.MesHttpTabPage }); this.ProtocolTabControl.Dock = System.Windows.Forms.DockStyle.Fill; this.ProtocolTabControl.Name = "ProtocolTabControl";
            this.ModbusTcpConnectButton.Click += new System.EventHandler(this.ModbusTcpConnectButton_Click); this.ModbusRtuConnectButton.Click += new System.EventHandler(this.ModbusRtuConnectButton_Click); this.S7ConnectButton.Click += new System.EventHandler(this.S7ConnectButton_Click); this.McConnectButton.Click += new System.EventHandler(this.McConnectButton_Click);
            this.ModbusTcpReadButton.Click += new System.EventHandler(this.IndustrialReadButton_Click); this.ModbusRtuReadButton.Click += new System.EventHandler(this.IndustrialReadButton_Click); this.S7ReadButton.Click += new System.EventHandler(this.IndustrialReadButton_Click); this.McReadButton.Click += new System.EventHandler(this.IndustrialReadButton_Click);
            this.ModbusTcpWriteButton.Click += new System.EventHandler(this.IndustrialWriteButton_Click); this.ModbusRtuWriteButton.Click += new System.EventHandler(this.IndustrialWriteButton_Click); this.S7WriteButton.Click += new System.EventHandler(this.IndustrialWriteButton_Click); this.McWriteButton.Click += new System.EventHandler(this.IndustrialWriteButton_Click);
            this.ModbusTcpDisconnectButton.Click += new System.EventHandler(this.IndustrialDisconnectButton_Click); this.ModbusRtuDisconnectButton.Click += new System.EventHandler(this.IndustrialDisconnectButton_Click); this.S7DisconnectButton.Click += new System.EventHandler(this.IndustrialDisconnectButton_Click); this.McDisconnectButton.Click += new System.EventHandler(this.IndustrialDisconnectButton_Click);
            this.RawTcpConnectButton.Click += new System.EventHandler(this.RawTcpConnectButton_Click); this.RawTcpSendButton.Click += new System.EventHandler(this.RawTcpSendButton_Click); this.RawTcpDisconnectButton.Click += new System.EventHandler(this.RawTcpDisconnectButton_Click); this.MesTcpConnectButton.Click += new System.EventHandler(this.MesTcpConnectButton_Click); this.MesTcpOnlineButton.Click += new System.EventHandler(this.MesTcpOnlineButton_Click); this.MesTcpDisconnectButton.Click += new System.EventHandler(this.MesTcpDisconnectButton_Click); this.MesHttpOnlineButton.Click += new System.EventHandler(this.MesHttpOnlineButton_Click);
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 17F); this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font; this.ClientSize = new System.Drawing.Size(984, 681); this.Controls.Add(this.ProtocolTabControl); this.Name = "MainForm"; this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen; this.Text = "IndustrialCommSdk 协议最小系统"; this.ResumeLayout(false);
        }

        private static System.Windows.Forms.TextBox NewTextBox(string text) { return new System.Windows.Forms.TextBox { Text = text, Width = 820, Margin = new System.Windows.Forms.Padding(6) }; }
        private static System.Windows.Forms.TextBox NewOutputTextBox() { return new System.Windows.Forms.TextBox { Multiline = true, ReadOnly = true, ScrollBars = System.Windows.Forms.ScrollBars.Vertical, Width = 900, Height = 260, Margin = new System.Windows.Forms.Padding(6) }; }
        private static System.Windows.Forms.ComboBox NewTypeComboBox() { var box = new System.Windows.Forms.ComboBox { DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList, Width = 820, Margin = new System.Windows.Forms.Padding(6) }; box.Items.AddRange(new object[] { "Bool", "Int16", "UInt16", "Int32", "UInt32", "Float", "Double", "Byte", "Char", "String", "ByteArray" }); box.SelectedIndex = 1; return box; }
        private static System.Windows.Forms.Button NewButton(string text) { return new System.Windows.Forms.Button { Text = text, AutoSize = true, Margin = new System.Windows.Forms.Padding(6) }; }
        private static System.Windows.Forms.Label NewLabel(string text) { return new System.Windows.Forms.Label { Text = text, AutoSize = false, Width = 900, Height = 20, Margin = new System.Windows.Forms.Padding(6, 8, 6, 0) }; }
        private static void SetupPage(System.Windows.Forms.TabPage page, System.Windows.Forms.FlowLayoutPanel panel, string text, System.Windows.Forms.Control[] controls) { page.Text = text; page.Padding = new System.Windows.Forms.Padding(3); panel.Dock = System.Windows.Forms.DockStyle.Fill; panel.FlowDirection = System.Windows.Forms.FlowDirection.TopDown; panel.WrapContents = false; panel.AutoScroll = true; panel.Controls.AddRange(controls); page.Controls.Add(panel); }
    }
}
