namespace IndustrialCommMinimal.WinForms
{
    // 本文件由 Visual Studio WinForms 设计器维护。
    // 这里只保存控件声明、布局属性和事件绑定；协议通讯逻辑统一放在 MainForm.cs 中。
    // 手工修改后应立即用“查看设计器”验证，避免破坏设计器的代码序列化结构。
    partial class MainForm
    {
        private System.ComponentModel.IContainer components = null;
        private System.Windows.Forms.TabControl ProtocolTabControl;
        private System.Windows.Forms.TabPage ModbusTcpTabPage, ModbusRtuTabPage, S7TabPage, McTabPage, RawTcpTabPage, MesTcpTabPage, MesHttpTabPage;
        private System.Windows.Forms.FlowLayoutPanel ModbusTcpPanel, ModbusRtuPanel, S7Panel, McPanel, RawTcpPanel, MesTcpPanel, MesHttpPanel;
        private System.Windows.Forms.Label label1, label2, label3, label4, label5, label6, label7, label8, label9, label10, label11, label12, label13, label14, label15, label16, label17, label18, label19, label20, label21, label22, label23, label24, label25, label26, label27, label28, label29, label30, label31, label32, label33, label34, label35, label36, label37, label38, label39, label40, label41;
        private System.Windows.Forms.TextBox ModbusTcpHostTextBox, ModbusTcpPortTextBox, ModbusTcpSlaveTextBox, ModbusTcpAddressTextBox, ModbusTcpValueTextBox, ModbusTcpOutputTextBox;
        private System.Windows.Forms.ComboBox ModbusTcpTypeComboBox;
        private System.Windows.Forms.Button ModbusTcpConnectButton, ModbusTcpReadButton, ModbusTcpWriteButton, ModbusTcpDisconnectButton;
        private System.Windows.Forms.TextBox ModbusRtuPortTextBox, ModbusRtuBaudTextBox, ModbusRtuSlaveTextBox, ModbusRtuAddressTextBox, ModbusRtuValueTextBox, ModbusRtuOutputTextBox;
        private System.Windows.Forms.ComboBox ModbusRtuTypeComboBox;
        private System.Windows.Forms.Button ModbusRtuConnectButton, ModbusRtuReadButton, ModbusRtuWriteButton, ModbusRtuDisconnectButton;
        private System.Windows.Forms.TextBox S7HostTextBox, S7RackTextBox, S7SlotTextBox, S7AddressTextBox, S7ValueTextBox, S7OutputTextBox;
        private System.Windows.Forms.ComboBox S7TypeComboBox;
        private System.Windows.Forms.Button S7ConnectButton, S7ReadButton, S7WriteButton, S7DisconnectButton;
        private System.Windows.Forms.TextBox McHostTextBox, McPortTextBox, McTimeoutTextBox, McAddressTextBox, McValueTextBox, McOutputTextBox;
        private System.Windows.Forms.ComboBox McTypeComboBox;
        private System.Windows.Forms.Button McConnectButton, McReadButton, McWriteButton, McDisconnectButton;
        private System.Windows.Forms.TextBox RawTcpHostTextBox, RawTcpPortTextBox, RawTcpPayloadTextBox, RawTcpDelimiterTextBox, RawTcpFrameLengthTextBox, RawTcpMaximumFrameLengthTextBox, RawTcpOutputTextBox;
        private System.Windows.Forms.ComboBox RawTcpFramingComboBox;
        private System.Windows.Forms.Button RawTcpConnectButton, RawTcpSendButton, RawTcpDisconnectButton;
        private System.Windows.Forms.TextBox MesTcpHostTextBox, MesTcpPortTextBox, MesTcpDeviceNoTextBox, MesTcpDeviceNameTextBox, MesTcpDeviceIpTextBox, MesTcpDeviceMacTextBox, MesTcpOutputTextBox;
        private System.Windows.Forms.Button MesTcpConnectButton, MesTcpOnlineButton, MesTcpDisconnectButton;
        private System.Windows.Forms.TextBox MesHttpUrlTextBox, MesHttpDeviceNoTextBox, MesHttpDeviceNameTextBox, MesHttpDeviceIpTextBox, MesHttpDeviceMacTextBox, MesHttpOutputTextBox;
        private System.Windows.Forms.Button MesHttpOnlineButton;

        /// <summary>释放设计器创建并登记在 components 容器中的控件资源。</summary>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null)) components.Dispose();
            base.Dispose(disposing);
        }

        /// <summary>
        /// 创建七个协议页签及其输入、操作和日志控件，并绑定 MainForm.cs 中的事件处理方法。
        /// 此方法只应由窗体构造函数调用。
        /// </summary>
        private void InitializeComponent()
        {
            this.ProtocolTabControl = new System.Windows.Forms.TabControl();
            this.ModbusTcpTabPage = new System.Windows.Forms.TabPage(); this.ModbusRtuTabPage = new System.Windows.Forms.TabPage(); this.S7TabPage = new System.Windows.Forms.TabPage(); this.McTabPage = new System.Windows.Forms.TabPage(); this.RawTcpTabPage = new System.Windows.Forms.TabPage(); this.MesTcpTabPage = new System.Windows.Forms.TabPage(); this.MesHttpTabPage = new System.Windows.Forms.TabPage();
            this.ModbusTcpPanel = new System.Windows.Forms.FlowLayoutPanel(); this.ModbusRtuPanel = new System.Windows.Forms.FlowLayoutPanel(); this.S7Panel = new System.Windows.Forms.FlowLayoutPanel(); this.McPanel = new System.Windows.Forms.FlowLayoutPanel(); this.RawTcpPanel = new System.Windows.Forms.FlowLayoutPanel(); this.MesTcpPanel = new System.Windows.Forms.FlowLayoutPanel(); this.MesHttpPanel = new System.Windows.Forms.FlowLayoutPanel();
            this.label1 = new System.Windows.Forms.Label(); this.label2 = new System.Windows.Forms.Label(); this.label3 = new System.Windows.Forms.Label(); this.label4 = new System.Windows.Forms.Label(); this.label5 = new System.Windows.Forms.Label(); this.label6 = new System.Windows.Forms.Label(); this.label7 = new System.Windows.Forms.Label(); this.label8 = new System.Windows.Forms.Label(); this.label9 = new System.Windows.Forms.Label(); this.label10 = new System.Windows.Forms.Label(); this.label11 = new System.Windows.Forms.Label(); this.label12 = new System.Windows.Forms.Label(); this.label13 = new System.Windows.Forms.Label(); this.label14 = new System.Windows.Forms.Label(); this.label15 = new System.Windows.Forms.Label(); this.label16 = new System.Windows.Forms.Label(); this.label17 = new System.Windows.Forms.Label(); this.label18 = new System.Windows.Forms.Label(); this.label19 = new System.Windows.Forms.Label(); this.label20 = new System.Windows.Forms.Label(); this.label21 = new System.Windows.Forms.Label(); this.label22 = new System.Windows.Forms.Label(); this.label23 = new System.Windows.Forms.Label(); this.label24 = new System.Windows.Forms.Label(); this.label25 = new System.Windows.Forms.Label(); this.label26 = new System.Windows.Forms.Label(); this.label27 = new System.Windows.Forms.Label(); this.label28 = new System.Windows.Forms.Label(); this.label29 = new System.Windows.Forms.Label(); this.label30 = new System.Windows.Forms.Label(); this.label31 = new System.Windows.Forms.Label(); this.label32 = new System.Windows.Forms.Label(); this.label33 = new System.Windows.Forms.Label(); this.label34 = new System.Windows.Forms.Label(); this.label35 = new System.Windows.Forms.Label(); this.label36 = new System.Windows.Forms.Label(); this.label37 = new System.Windows.Forms.Label(); this.label38 = new System.Windows.Forms.Label(); this.label39 = new System.Windows.Forms.Label(); this.label40 = new System.Windows.Forms.Label(); this.label41 = new System.Windows.Forms.Label();
            this.ModbusTcpHostTextBox = new System.Windows.Forms.TextBox(); this.ModbusTcpPortTextBox = new System.Windows.Forms.TextBox(); this.ModbusTcpSlaveTextBox = new System.Windows.Forms.TextBox(); this.ModbusTcpAddressTextBox = new System.Windows.Forms.TextBox(); this.ModbusTcpValueTextBox = new System.Windows.Forms.TextBox(); this.ModbusTcpTypeComboBox = new System.Windows.Forms.ComboBox(); this.ModbusTcpOutputTextBox = new System.Windows.Forms.TextBox(); this.ModbusTcpConnectButton = new System.Windows.Forms.Button(); this.ModbusTcpReadButton = new System.Windows.Forms.Button(); this.ModbusTcpWriteButton = new System.Windows.Forms.Button(); this.ModbusTcpDisconnectButton = new System.Windows.Forms.Button();
            this.ModbusRtuPortTextBox = new System.Windows.Forms.TextBox(); this.ModbusRtuBaudTextBox = new System.Windows.Forms.TextBox(); this.ModbusRtuSlaveTextBox = new System.Windows.Forms.TextBox(); this.ModbusRtuAddressTextBox = new System.Windows.Forms.TextBox(); this.ModbusRtuValueTextBox = new System.Windows.Forms.TextBox(); this.ModbusRtuTypeComboBox = new System.Windows.Forms.ComboBox(); this.ModbusRtuOutputTextBox = new System.Windows.Forms.TextBox(); this.ModbusRtuConnectButton = new System.Windows.Forms.Button(); this.ModbusRtuReadButton = new System.Windows.Forms.Button(); this.ModbusRtuWriteButton = new System.Windows.Forms.Button(); this.ModbusRtuDisconnectButton = new System.Windows.Forms.Button();
            this.S7HostTextBox = new System.Windows.Forms.TextBox(); this.S7RackTextBox = new System.Windows.Forms.TextBox(); this.S7SlotTextBox = new System.Windows.Forms.TextBox(); this.S7AddressTextBox = new System.Windows.Forms.TextBox(); this.S7ValueTextBox = new System.Windows.Forms.TextBox(); this.S7TypeComboBox = new System.Windows.Forms.ComboBox(); this.S7OutputTextBox = new System.Windows.Forms.TextBox(); this.S7ConnectButton = new System.Windows.Forms.Button(); this.S7ReadButton = new System.Windows.Forms.Button(); this.S7WriteButton = new System.Windows.Forms.Button(); this.S7DisconnectButton = new System.Windows.Forms.Button();
            this.McHostTextBox = new System.Windows.Forms.TextBox(); this.McPortTextBox = new System.Windows.Forms.TextBox(); this.McTimeoutTextBox = new System.Windows.Forms.TextBox(); this.McAddressTextBox = new System.Windows.Forms.TextBox(); this.McValueTextBox = new System.Windows.Forms.TextBox(); this.McTypeComboBox = new System.Windows.Forms.ComboBox(); this.McOutputTextBox = new System.Windows.Forms.TextBox(); this.McConnectButton = new System.Windows.Forms.Button(); this.McReadButton = new System.Windows.Forms.Button(); this.McWriteButton = new System.Windows.Forms.Button(); this.McDisconnectButton = new System.Windows.Forms.Button();
            this.RawTcpHostTextBox = new System.Windows.Forms.TextBox(); this.RawTcpPortTextBox = new System.Windows.Forms.TextBox(); this.RawTcpPayloadTextBox = new System.Windows.Forms.TextBox(); this.RawTcpDelimiterTextBox = new System.Windows.Forms.TextBox(); this.RawTcpFrameLengthTextBox = new System.Windows.Forms.TextBox(); this.RawTcpMaximumFrameLengthTextBox = new System.Windows.Forms.TextBox(); this.RawTcpFramingComboBox = new System.Windows.Forms.ComboBox(); this.RawTcpOutputTextBox = new System.Windows.Forms.TextBox(); this.RawTcpConnectButton = new System.Windows.Forms.Button(); this.RawTcpSendButton = new System.Windows.Forms.Button(); this.RawTcpDisconnectButton = new System.Windows.Forms.Button();
            this.MesTcpHostTextBox = new System.Windows.Forms.TextBox(); this.MesTcpPortTextBox = new System.Windows.Forms.TextBox(); this.MesTcpDeviceNoTextBox = new System.Windows.Forms.TextBox(); this.MesTcpDeviceNameTextBox = new System.Windows.Forms.TextBox(); this.MesTcpDeviceIpTextBox = new System.Windows.Forms.TextBox(); this.MesTcpDeviceMacTextBox = new System.Windows.Forms.TextBox(); this.MesTcpOutputTextBox = new System.Windows.Forms.TextBox(); this.MesTcpConnectButton = new System.Windows.Forms.Button(); this.MesTcpOnlineButton = new System.Windows.Forms.Button(); this.MesTcpDisconnectButton = new System.Windows.Forms.Button();
            this.MesHttpUrlTextBox = new System.Windows.Forms.TextBox(); this.MesHttpDeviceNoTextBox = new System.Windows.Forms.TextBox(); this.MesHttpDeviceNameTextBox = new System.Windows.Forms.TextBox(); this.MesHttpDeviceIpTextBox = new System.Windows.Forms.TextBox(); this.MesHttpDeviceMacTextBox = new System.Windows.Forms.TextBox(); this.MesHttpOutputTextBox = new System.Windows.Forms.TextBox(); this.MesHttpOnlineButton = new System.Windows.Forms.Button();
            this.ProtocolTabControl.SuspendLayout(); this.ModbusTcpTabPage.SuspendLayout(); this.ModbusRtuTabPage.SuspendLayout(); this.S7TabPage.SuspendLayout(); this.McTabPage.SuspendLayout(); this.RawTcpTabPage.SuspendLayout(); this.MesTcpTabPage.SuspendLayout(); this.MesHttpTabPage.SuspendLayout(); this.SuspendLayout();

            this.ProtocolTabControl.Controls.Add(this.ModbusTcpTabPage); this.ProtocolTabControl.Controls.Add(this.ModbusRtuTabPage); this.ProtocolTabControl.Controls.Add(this.S7TabPage); this.ProtocolTabControl.Controls.Add(this.McTabPage); this.ProtocolTabControl.Controls.Add(this.RawTcpTabPage); this.ProtocolTabControl.Controls.Add(this.MesTcpTabPage); this.ProtocolTabControl.Controls.Add(this.MesHttpTabPage); this.ProtocolTabControl.Dock = System.Windows.Forms.DockStyle.Fill; this.ProtocolTabControl.Name = "ProtocolTabControl"; this.ProtocolTabControl.SelectedIndex = 0;
            this.ModbusTcpTabPage.Controls.Add(this.ModbusTcpPanel); this.ModbusTcpTabPage.Text = "Modbus TCP"; this.ModbusRtuTabPage.Controls.Add(this.ModbusRtuPanel); this.ModbusRtuTabPage.Text = "Modbus RTU"; this.S7TabPage.Controls.Add(this.S7Panel); this.S7TabPage.Text = "Siemens S7"; this.McTabPage.Controls.Add(this.McPanel); this.McTabPage.Text = "Mitsubishi MC"; this.RawTcpTabPage.Controls.Add(this.RawTcpPanel); this.RawTcpTabPage.Text = "原始 TCP"; this.MesTcpTabPage.Controls.Add(this.MesTcpPanel); this.MesTcpTabPage.Text = "MES TCP"; this.MesHttpTabPage.Controls.Add(this.MesHttpPanel); this.MesHttpTabPage.Text = "MES HTTP";
            this.ModbusTcpPanel.Dock = System.Windows.Forms.DockStyle.Fill; this.ModbusTcpPanel.FlowDirection = System.Windows.Forms.FlowDirection.TopDown; this.ModbusTcpPanel.WrapContents = false; this.ModbusTcpPanel.AutoScroll = true;
            this.ModbusRtuPanel.Dock = System.Windows.Forms.DockStyle.Fill; this.ModbusRtuPanel.FlowDirection = System.Windows.Forms.FlowDirection.TopDown; this.ModbusRtuPanel.WrapContents = false; this.ModbusRtuPanel.AutoScroll = true;
            this.S7Panel.Dock = System.Windows.Forms.DockStyle.Fill; this.S7Panel.FlowDirection = System.Windows.Forms.FlowDirection.TopDown; this.S7Panel.WrapContents = false; this.S7Panel.AutoScroll = true;
            this.McPanel.Dock = System.Windows.Forms.DockStyle.Fill; this.McPanel.FlowDirection = System.Windows.Forms.FlowDirection.TopDown; this.McPanel.WrapContents = false; this.McPanel.AutoScroll = true;
            this.RawTcpPanel.Dock = System.Windows.Forms.DockStyle.Fill; this.RawTcpPanel.FlowDirection = System.Windows.Forms.FlowDirection.TopDown; this.RawTcpPanel.WrapContents = false; this.RawTcpPanel.AutoScroll = true;
            this.MesTcpPanel.Dock = System.Windows.Forms.DockStyle.Fill; this.MesTcpPanel.FlowDirection = System.Windows.Forms.FlowDirection.TopDown; this.MesTcpPanel.WrapContents = false; this.MesTcpPanel.AutoScroll = true;
            this.MesHttpPanel.Dock = System.Windows.Forms.DockStyle.Fill; this.MesHttpPanel.FlowDirection = System.Windows.Forms.FlowDirection.TopDown; this.MesHttpPanel.WrapContents = false; this.MesHttpPanel.AutoScroll = true;

            this.label1.Text = "主机"; this.label2.Text = "端口"; this.label3.Text = "站号"; this.label4.Text = "地址"; this.label5.Text = "数据类型"; this.label6.Text = "写入值";
            this.ModbusTcpHostTextBox.Text = "127.0.0.1"; this.ModbusTcpPortTextBox.Text = "502"; this.ModbusTcpSlaveTextBox.Text = "1"; this.ModbusTcpAddressTextBox.Text = "HR0"; this.ModbusTcpValueTextBox.Text = "0"; this.ModbusTcpTypeComboBox.Items.AddRange(new object[] { "Bool", "Int16", "UInt16", "Int32", "UInt32", "Float", "Double", "Byte", "Char", "String", "ByteArray" }); this.ModbusTcpTypeComboBox.Text = "Int16"; this.ModbusTcpConnectButton.Text = "连接"; this.ModbusTcpReadButton.Text = "读取"; this.ModbusTcpWriteButton.Text = "写入"; this.ModbusTcpDisconnectButton.Text = "断开";
            this.ModbusTcpPanel.Controls.Add(this.label1); this.ModbusTcpPanel.Controls.Add(this.ModbusTcpHostTextBox); this.ModbusTcpPanel.Controls.Add(this.label2); this.ModbusTcpPanel.Controls.Add(this.ModbusTcpPortTextBox); this.ModbusTcpPanel.Controls.Add(this.label3); this.ModbusTcpPanel.Controls.Add(this.ModbusTcpSlaveTextBox); this.ModbusTcpPanel.Controls.Add(this.label4); this.ModbusTcpPanel.Controls.Add(this.ModbusTcpAddressTextBox); this.ModbusTcpPanel.Controls.Add(this.label5); this.ModbusTcpPanel.Controls.Add(this.ModbusTcpTypeComboBox); this.ModbusTcpPanel.Controls.Add(this.label6); this.ModbusTcpPanel.Controls.Add(this.ModbusTcpValueTextBox); this.ModbusTcpPanel.Controls.Add(this.ModbusTcpConnectButton); this.ModbusTcpPanel.Controls.Add(this.ModbusTcpReadButton); this.ModbusTcpPanel.Controls.Add(this.ModbusTcpWriteButton); this.ModbusTcpPanel.Controls.Add(this.ModbusTcpDisconnectButton); this.ModbusTcpPanel.Controls.Add(this.ModbusTcpOutputTextBox);

            this.label7.Text = "串口"; this.label8.Text = "波特率"; this.label9.Text = "站号"; this.label10.Text = "地址"; this.label11.Text = "数据类型"; this.label12.Text = "写入值";
            this.ModbusRtuPortTextBox.Text = "COM3"; this.ModbusRtuBaudTextBox.Text = "9600"; this.ModbusRtuSlaveTextBox.Text = "1"; this.ModbusRtuAddressTextBox.Text = "HR0"; this.ModbusRtuValueTextBox.Text = "0"; this.ModbusRtuTypeComboBox.Items.AddRange(new object[] { "Bool", "Int16", "UInt16", "Int32", "UInt32", "Float", "Double", "Byte", "Char", "String", "ByteArray" }); this.ModbusRtuTypeComboBox.Text = "Int16"; this.ModbusRtuConnectButton.Text = "连接"; this.ModbusRtuReadButton.Text = "读取"; this.ModbusRtuWriteButton.Text = "写入"; this.ModbusRtuDisconnectButton.Text = "断开";
            this.ModbusRtuPanel.Controls.Add(this.label7); this.ModbusRtuPanel.Controls.Add(this.ModbusRtuPortTextBox); this.ModbusRtuPanel.Controls.Add(this.label8); this.ModbusRtuPanel.Controls.Add(this.ModbusRtuBaudTextBox); this.ModbusRtuPanel.Controls.Add(this.label9); this.ModbusRtuPanel.Controls.Add(this.ModbusRtuSlaveTextBox); this.ModbusRtuPanel.Controls.Add(this.label10); this.ModbusRtuPanel.Controls.Add(this.ModbusRtuAddressTextBox); this.ModbusRtuPanel.Controls.Add(this.label11); this.ModbusRtuPanel.Controls.Add(this.ModbusRtuTypeComboBox); this.ModbusRtuPanel.Controls.Add(this.label12); this.ModbusRtuPanel.Controls.Add(this.ModbusRtuValueTextBox); this.ModbusRtuPanel.Controls.Add(this.ModbusRtuConnectButton); this.ModbusRtuPanel.Controls.Add(this.ModbusRtuReadButton); this.ModbusRtuPanel.Controls.Add(this.ModbusRtuWriteButton); this.ModbusRtuPanel.Controls.Add(this.ModbusRtuDisconnectButton); this.ModbusRtuPanel.Controls.Add(this.ModbusRtuOutputTextBox);

            this.label13.Text = "主机"; this.label14.Text = "机架"; this.label15.Text = "插槽"; this.label16.Text = "地址"; this.label17.Text = "数据类型"; this.label18.Text = "写入值";
            this.S7HostTextBox.Text = "127.0.0.1"; this.S7RackTextBox.Text = "0"; this.S7SlotTextBox.Text = "1"; this.S7AddressTextBox.Text = "DB1.DBW0"; this.S7ValueTextBox.Text = "0"; this.S7TypeComboBox.Items.AddRange(new object[] { "Bool", "Int16", "UInt16", "Int32", "UInt32", "Float", "Double", "Byte", "Char", "String", "ByteArray" }); this.S7TypeComboBox.Text = "Int16"; this.S7ConnectButton.Text = "连接"; this.S7ReadButton.Text = "读取"; this.S7WriteButton.Text = "写入"; this.S7DisconnectButton.Text = "断开";
            this.S7Panel.Controls.Add(this.label13); this.S7Panel.Controls.Add(this.S7HostTextBox); this.S7Panel.Controls.Add(this.label14); this.S7Panel.Controls.Add(this.S7RackTextBox); this.S7Panel.Controls.Add(this.label15); this.S7Panel.Controls.Add(this.S7SlotTextBox); this.S7Panel.Controls.Add(this.label16); this.S7Panel.Controls.Add(this.S7AddressTextBox); this.S7Panel.Controls.Add(this.label17); this.S7Panel.Controls.Add(this.S7TypeComboBox); this.S7Panel.Controls.Add(this.label18); this.S7Panel.Controls.Add(this.S7ValueTextBox); this.S7Panel.Controls.Add(this.S7ConnectButton); this.S7Panel.Controls.Add(this.S7ReadButton); this.S7Panel.Controls.Add(this.S7WriteButton); this.S7Panel.Controls.Add(this.S7DisconnectButton); this.S7Panel.Controls.Add(this.S7OutputTextBox);

            this.label19.Text = "主机"; this.label20.Text = "端口"; this.label21.Text = "接收超时(ms)"; this.label22.Text = "地址"; this.label23.Text = "数据类型"; this.label24.Text = "写入值";
            this.McHostTextBox.Text = "127.0.0.1"; this.McPortTextBox.Text = "5000"; this.McTimeoutTextBox.Text = "5000"; this.McAddressTextBox.Text = "D100"; this.McValueTextBox.Text = "0"; this.McTypeComboBox.Items.AddRange(new object[] { "Bool", "Int16", "UInt16", "Int32", "UInt32", "Float", "Double", "Byte", "Char", "String", "ByteArray" }); this.McTypeComboBox.Text = "Int16"; this.McConnectButton.Text = "连接"; this.McReadButton.Text = "读取"; this.McWriteButton.Text = "写入"; this.McDisconnectButton.Text = "断开";
            this.McPanel.Controls.Add(this.label19); this.McPanel.Controls.Add(this.McHostTextBox); this.McPanel.Controls.Add(this.label20); this.McPanel.Controls.Add(this.McPortTextBox); this.McPanel.Controls.Add(this.label21); this.McPanel.Controls.Add(this.McTimeoutTextBox); this.McPanel.Controls.Add(this.label22); this.McPanel.Controls.Add(this.McAddressTextBox); this.McPanel.Controls.Add(this.label23); this.McPanel.Controls.Add(this.McTypeComboBox); this.McPanel.Controls.Add(this.label24); this.McPanel.Controls.Add(this.McValueTextBox); this.McPanel.Controls.Add(this.McConnectButton); this.McPanel.Controls.Add(this.McReadButton); this.McPanel.Controls.Add(this.McWriteButton); this.McPanel.Controls.Add(this.McDisconnectButton); this.McPanel.Controls.Add(this.McOutputTextBox);

            this.label25.Text = "主机"; this.label26.Text = "端口"; this.label27.Text = "发送文本"; this.label38.Text = "分帧模式"; this.label39.Text = "分隔符(支持 \\r \\n \\0)"; this.label40.Text = "固定帧长"; this.label41.Text = "最大帧长"; this.RawTcpHostTextBox.Text = "127.0.0.1"; this.RawTcpPortTextBox.Text = "9000"; this.RawTcpPayloadTextBox.Text = "hello"; this.RawTcpDelimiterTextBox.Text = "\\r\\n"; this.RawTcpFrameLengthTextBox.Text = "8"; this.RawTcpMaximumFrameLengthTextBox.Text = "1048576"; this.RawTcpFramingComboBox.Items.AddRange(new object[] { "原始字节流", "固定长度", "分隔符", "2字节长度头", "4字节长度头" }); this.RawTcpFramingComboBox.Text = "原始字节流"; this.RawTcpConnectButton.Text = "连接"; this.RawTcpSendButton.Text = "发送并接收"; this.RawTcpDisconnectButton.Text = "断开";
            this.RawTcpPanel.Controls.Add(this.label25); this.RawTcpPanel.Controls.Add(this.RawTcpHostTextBox); this.RawTcpPanel.Controls.Add(this.label26); this.RawTcpPanel.Controls.Add(this.RawTcpPortTextBox); this.RawTcpPanel.Controls.Add(this.label38); this.RawTcpPanel.Controls.Add(this.RawTcpFramingComboBox); this.RawTcpPanel.Controls.Add(this.label39); this.RawTcpPanel.Controls.Add(this.RawTcpDelimiterTextBox); this.RawTcpPanel.Controls.Add(this.label40); this.RawTcpPanel.Controls.Add(this.RawTcpFrameLengthTextBox); this.RawTcpPanel.Controls.Add(this.label41); this.RawTcpPanel.Controls.Add(this.RawTcpMaximumFrameLengthTextBox); this.RawTcpPanel.Controls.Add(this.label27); this.RawTcpPanel.Controls.Add(this.RawTcpPayloadTextBox); this.RawTcpPanel.Controls.Add(this.RawTcpConnectButton); this.RawTcpPanel.Controls.Add(this.RawTcpSendButton); this.RawTcpPanel.Controls.Add(this.RawTcpDisconnectButton); this.RawTcpPanel.Controls.Add(this.RawTcpOutputTextBox);

            this.label28.Text = "主机"; this.label29.Text = "端口"; this.label30.Text = "设备编号"; this.label31.Text = "设备名称"; this.label32.Text = "设备 IP"; this.label33.Text = "设备 MAC"; this.MesTcpHostTextBox.Text = "127.0.0.1"; this.MesTcpPortTextBox.Text = "9312"; this.MesTcpDeviceNoTextBox.Text = "DEVICE-001"; this.MesTcpDeviceNameTextBox.Text = "MinimalClient"; this.MesTcpDeviceIpTextBox.Text = "127.0.0.1"; this.MesTcpDeviceMacTextBox.Text = "00-00-00-00-00-00"; this.MesTcpConnectButton.Text = "连接"; this.MesTcpOnlineButton.Text = "发送上线"; this.MesTcpDisconnectButton.Text = "断开";
            this.MesTcpPanel.Controls.Add(this.label28); this.MesTcpPanel.Controls.Add(this.MesTcpHostTextBox); this.MesTcpPanel.Controls.Add(this.label29); this.MesTcpPanel.Controls.Add(this.MesTcpPortTextBox); this.MesTcpPanel.Controls.Add(this.label30); this.MesTcpPanel.Controls.Add(this.MesTcpDeviceNoTextBox); this.MesTcpPanel.Controls.Add(this.label31); this.MesTcpPanel.Controls.Add(this.MesTcpDeviceNameTextBox); this.MesTcpPanel.Controls.Add(this.label32); this.MesTcpPanel.Controls.Add(this.MesTcpDeviceIpTextBox); this.MesTcpPanel.Controls.Add(this.label33); this.MesTcpPanel.Controls.Add(this.MesTcpDeviceMacTextBox); this.MesTcpPanel.Controls.Add(this.MesTcpConnectButton); this.MesTcpPanel.Controls.Add(this.MesTcpOnlineButton); this.MesTcpPanel.Controls.Add(this.MesTcpDisconnectButton); this.MesTcpPanel.Controls.Add(this.MesTcpOutputTextBox);

            this.label34.Text = "API 地址"; this.label35.Text = "设备编号"; this.label36.Text = "设备名称"; this.label37.Text = "设备 IP / MAC"; this.MesHttpUrlTextBox.Text = "http://127.0.0.1:8080/api"; this.MesHttpDeviceNoTextBox.Text = "DEVICE-001"; this.MesHttpDeviceNameTextBox.Text = "MinimalClient"; this.MesHttpDeviceIpTextBox.Text = "127.0.0.1"; this.MesHttpDeviceMacTextBox.Text = "00-00-00-00-00-00"; this.MesHttpOnlineButton.Text = "发送上线";
            this.MesHttpPanel.Controls.Add(this.label34); this.MesHttpPanel.Controls.Add(this.MesHttpUrlTextBox); this.MesHttpPanel.Controls.Add(this.label35); this.MesHttpPanel.Controls.Add(this.MesHttpDeviceNoTextBox); this.MesHttpPanel.Controls.Add(this.label36); this.MesHttpPanel.Controls.Add(this.MesHttpDeviceNameTextBox); this.MesHttpPanel.Controls.Add(this.label37); this.MesHttpPanel.Controls.Add(this.MesHttpDeviceIpTextBox); this.MesHttpPanel.Controls.Add(this.MesHttpDeviceMacTextBox); this.MesHttpPanel.Controls.Add(this.MesHttpOnlineButton); this.MesHttpPanel.Controls.Add(this.MesHttpOutputTextBox);

            this.ModbusTcpOutputTextBox.Multiline = true; this.ModbusRtuOutputTextBox.Multiline = true; this.S7OutputTextBox.Multiline = true; this.McOutputTextBox.Multiline = true; this.RawTcpOutputTextBox.Multiline = true; this.MesTcpOutputTextBox.Multiline = true; this.MesHttpOutputTextBox.Multiline = true;
            this.ModbusTcpOutputTextBox.Size = new System.Drawing.Size(850, 220); this.ModbusRtuOutputTextBox.Size = new System.Drawing.Size(850, 220); this.S7OutputTextBox.Size = new System.Drawing.Size(850, 220); this.McOutputTextBox.Size = new System.Drawing.Size(850, 220); this.RawTcpOutputTextBox.Size = new System.Drawing.Size(850, 220); this.MesTcpOutputTextBox.Size = new System.Drawing.Size(850, 220); this.MesHttpOutputTextBox.Size = new System.Drawing.Size(850, 220);
            this.ModbusTcpConnectButton.Click += new System.EventHandler(this.ModbusTcpConnectButton_Click); this.ModbusRtuConnectButton.Click += new System.EventHandler(this.ModbusRtuConnectButton_Click); this.S7ConnectButton.Click += new System.EventHandler(this.S7ConnectButton_Click); this.McConnectButton.Click += new System.EventHandler(this.McConnectButton_Click); this.ModbusTcpReadButton.Click += new System.EventHandler(this.IndustrialReadButton_Click); this.ModbusRtuReadButton.Click += new System.EventHandler(this.IndustrialReadButton_Click); this.S7ReadButton.Click += new System.EventHandler(this.IndustrialReadButton_Click); this.McReadButton.Click += new System.EventHandler(this.IndustrialReadButton_Click); this.ModbusTcpWriteButton.Click += new System.EventHandler(this.IndustrialWriteButton_Click); this.ModbusRtuWriteButton.Click += new System.EventHandler(this.IndustrialWriteButton_Click); this.S7WriteButton.Click += new System.EventHandler(this.IndustrialWriteButton_Click); this.McWriteButton.Click += new System.EventHandler(this.IndustrialWriteButton_Click); this.ModbusTcpDisconnectButton.Click += new System.EventHandler(this.IndustrialDisconnectButton_Click); this.ModbusRtuDisconnectButton.Click += new System.EventHandler(this.IndustrialDisconnectButton_Click); this.S7DisconnectButton.Click += new System.EventHandler(this.IndustrialDisconnectButton_Click); this.McDisconnectButton.Click += new System.EventHandler(this.IndustrialDisconnectButton_Click); this.RawTcpConnectButton.Click += new System.EventHandler(this.RawTcpConnectButton_Click); this.RawTcpSendButton.Click += new System.EventHandler(this.RawTcpSendButton_Click); this.RawTcpDisconnectButton.Click += new System.EventHandler(this.RawTcpDisconnectButton_Click); this.MesTcpConnectButton.Click += new System.EventHandler(this.MesTcpConnectButton_Click); this.MesTcpOnlineButton.Click += new System.EventHandler(this.MesTcpOnlineButton_Click); this.MesTcpDisconnectButton.Click += new System.EventHandler(this.MesTcpDisconnectButton_Click); this.MesHttpOnlineButton.Click += new System.EventHandler(this.MesHttpOnlineButton_Click);
            this.ClientSize = new System.Drawing.Size(984, 681); this.Controls.Add(this.ProtocolTabControl); this.Name = "MainForm"; this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen; this.Text = "IndustrialCommSdk 协议最小系统";
            this.ProtocolTabControl.ResumeLayout(false); this.ModbusTcpTabPage.ResumeLayout(false); this.ModbusRtuTabPage.ResumeLayout(false); this.S7TabPage.ResumeLayout(false); this.McTabPage.ResumeLayout(false); this.RawTcpTabPage.ResumeLayout(false); this.MesTcpTabPage.ResumeLayout(false); this.MesHttpTabPage.ResumeLayout(false); this.ResumeLayout(false);
        }
    }
}
