<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <RootNamespace>InduLink.Web</RootNamespace>
    <AssemblyName>InduLink.Web</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\InduLink.Abstractions\InduLink.Abstractions.csproj" />
    <ProjectReference Include="..\InduLink.Runtime\InduLink.Runtime.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>
</Project>
