<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <RootNamespace>InduLink</RootNamespace>
    <AssemblyName>InduLink.Protocols.Mqtt</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\InduLink.Abstractions\InduLink.Abstractions.csproj" />
    <ProjectReference Include="..\InduLink.Runtime\InduLink.Runtime.csproj" />
    <ProjectReference Include="..\InduLink.Protocols.Common\InduLink.Protocols.Common.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MQTTnet" Version="4.3.7.1207" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>
</Project>
