<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <RootNamespace>InduLink</RootNamespace>
    <AssemblyName>InduLink.Protocols.S7</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\InduLink.Abstractions\InduLink.Abstractions.csproj" />
    <ProjectReference Include="..\InduLink.Runtime\InduLink.Runtime.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="S7netplus" Version="0.20.0" />
  </ItemGroup>
</Project>
