<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>latest</LangVersion>
    <RootNamespace>IndustrialCommSdk.Protocols.Ads</RootNamespace>
    <AssemblyName>IndustrialCommSdk.Protocols.Ads</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\IndustrialCommSdk.Abstractions\IndustrialCommSdk.Abstractions.csproj" />
    <ProjectReference Include="..\IndustrialCommSdk.Runtime\IndustrialCommSdk.Runtime.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="TwinCAT.Ads, Version=4.3.0.0, Culture=neutral, PublicKeyToken=180016cd49e5e8c3">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>lib\TwinCAT.Ads.dll</HintPath>
      <Private>True</Private>
    </Reference>
  </ItemGroup>
</Project>
