<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <RootNamespace>InduLink</RootNamespace>
    <AssemblyName>InduLink.FileTransfer.Ftp</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\InduLink.Abstractions\InduLink.Abstractions.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FluentFTP" Version="54.2.0" />
  </ItemGroup>
</Project>
