<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>latest</LangVersion>
    <RootNamespace>IndustrialCommSdk</RootNamespace>
    <AssemblyName>IndustrialCommSdk.FileTransfer.Ftp</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\IndustrialCommSdk.Abstractions\IndustrialCommSdk.Abstractions.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FluentFTP" Version="54.2.0" />
  </ItemGroup>
</Project>
